package com.sargije.web.poslovanje.model;
// Generated Apr 25, 2017 4:34:49 PM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name = "KORISNIK",  schema = "PUBLIC", catalog = "POSLOVANJE")
public class Korisnik implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7307593949800502112L;
	private Long korisnikId;
	@NotNull
	private Valuta valuta;
	@NotNull
	@Size(min=2, max=150)
	private String korisnikNaziv;
	private String korisnikAdresa;
	private BigDecimal pocetnoDugovanje;
	private Set<Porudzbenica> porudzbenicas = new HashSet<Porudzbenica>(0);
	private Set<Placanja> placanjas = new HashSet<Placanja>(0);
	
	public Korisnik() {
	}

	public Korisnik(Valuta valuta, String korisnikNaziv, String korisnikAdresa, BigDecimal pocetnoDugovanje, Set<Porudzbenica> porudzbenicas, Set<Placanja> placanjas) {
		this.valuta = valuta;
		this.korisnikNaziv = korisnikNaziv;
		this.korisnikAdresa = korisnikAdresa;
		this.pocetnoDugovanje = pocetnoDugovanje;
		this.porudzbenicas = porudzbenicas;
		this.placanjas = placanjas;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "KORISNIK_ID", unique = true, nullable = false)
	public Long getKorisnikId() {
		return this.korisnikId;
	}

	public void setKorisnikId(Long korisnikId) {
		this.korisnikId = korisnikId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VALUTA_ID")
	public Valuta getValuta() {
		return this.valuta;
	}

	public void setValuta(Valuta valuta) {
		this.valuta = valuta;
	}

	@Column(name = "KORISNIK_NAZIV", length = 40)
	public String getKorisnikNaziv() {
		return this.korisnikNaziv;
	}

	public void setPocetnoDugovanje(BigDecimal pocetnoDugovanje) {
		this.pocetnoDugovanje = pocetnoDugovanje;
	}
	
	@Column(name ="POCETNO_DUGOVANJE", precision = 15, scale = 2)
	public BigDecimal getPocetnoDugovanje() {
		return pocetnoDugovanje;
	}
	
	public void setKorisnikNaziv(String korisnikNaziv) {
		this.korisnikNaziv = korisnikNaziv;
	}

	@Column(name = "KORISNIK_ADRESA", length = 40)
	public String getKorisnikAdresa() {
		return this.korisnikAdresa;
	}

	public void setKorisnikAdresa(String korisnikAdresa) {
		this.korisnikAdresa = korisnikAdresa;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "korisnik")
	@OrderBy("porudzbenicaId")
	public Set<Porudzbenica> getPorudzbenicas() {
		return this.porudzbenicas;
	}

	public void setPorudzbenicas(Set<Porudzbenica> porudzbenicas) {
		this.porudzbenicas = porudzbenicas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "korisnik")
	@OrderBy("placanjaId")
	public Set<Placanja> getPlacanjas() {
		return this.placanjas;
	}

	public void setPlacanjas(Set<Placanja> placanjas) {
		this.placanjas = placanjas;
	}

}
