package com.sargije.web.poslovanje.model;
// Generated Apr 25, 2017 4:34:49 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Magacin generated by hbm2java
 */
@Entity
@Table(name = "MAGACIN",  schema = "PUBLIC", catalog = "POSLOVANJE")
public class Magacin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3257961512773977515L;
	private Long magacinId;
	private Roba roba;
	private Integer kolicina;

	public Magacin() {
	}

	public Magacin(Roba roba, Integer kolicina) {
		this.roba = roba;
		this.kolicina = kolicina;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAGACIN_ID", unique = true, nullable = false)
	public Long getMagacinId() {
		return this.magacinId;
	}

	public void setMagacinId(Long magacinId) {
		this.magacinId = magacinId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROBA_ID")
	public Roba getRoba() {
		return this.roba;
	}

	public void setRoba(Roba roba) {
		this.roba = roba;
	}

	@Column(name = "KOLICINA")
	public Integer getKolicina() {
		return this.kolicina;
	}

	public void setKolicina(Integer kolicina) {
		this.kolicina = kolicina;
	}

}
