package com.sargije.web.poslovanje.model;
// Generated Apr 25, 2017 4:34:49 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PorudzbenicaStavke generated by hbm2java
 */
@Entity
@Table(name = "PORUDZBENICA_STAVKE",  schema = "PUBLIC", catalog = "POSLOVANJE")
public class PorudzbenicaStavke implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8344208169658114275L;
	private PorudzbenicaStavkeId id;
	private Porudzbenica porudzbenica;
	private RobaCenovnik robaCenovnik;
	private Integer kolicina;

	public PorudzbenicaStavke() {
	}

	public PorudzbenicaStavke(PorudzbenicaStavkeId id, Porudzbenica porudzbenica) {
		this.id = id;
		this.porudzbenica = porudzbenica;
	}

	public PorudzbenicaStavke(PorudzbenicaStavkeId id, Porudzbenica porudzbenica, RobaCenovnik robaCenovnik, Integer kolicina) {
		this.id = id;
		this.porudzbenica = porudzbenica;
		this.robaCenovnik = robaCenovnik;
		this.kolicina = kolicina;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "porudzbenicaId", column = @Column(name = "PORUDZBENICA_ID", nullable = false)),
			@AttributeOverride(name = "porudzbenicaStavkaId", column = @Column(name = "PORUDZBENICA_STAVKA_ID", nullable = false)) })
	public PorudzbenicaStavkeId getId() {
		return this.id;
	}

	public void setId(PorudzbenicaStavkeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PORUDZBENICA_ID", nullable = false, insertable = false, updatable = false)
	public Porudzbenica getPorudzbenica() {
		return this.porudzbenica;
	}

	public void setPorudzbenica(Porudzbenica porudzbenica) {
		this.porudzbenica = porudzbenica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CENOVNIK_ID")
	public RobaCenovnik getRobaCenovnik() {
		return this.robaCenovnik;
	}

	public void setRobaCenovnik(RobaCenovnik robaCenovnik) {
		this.robaCenovnik = robaCenovnik;
	}

	@Column(name = "KOLICINA")
	public Integer getKolicina() {
		return this.kolicina;
	}

	public void setKolicina(Integer kolicina) {
		this.kolicina = kolicina;
	}

}
