package com.sargije.web.poslovanje.model;
// Generated Apr 25, 2017 4:34:49 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * RobaCenovnik generated by hbm2java
 */
@Entity
@Table(name = "ROBA_CENOVNIK",  schema = "PUBLIC", catalog = "POSLOVANJE")
public class RobaCenovnik implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7161759162291742600L;
	private Integer cenovnikId;
	private Roba roba;
	private Valuta valuta;
	@NotNull
	private BigDecimal cena;
	private Boolean aktivna;

	public RobaCenovnik() {
	}

	public RobaCenovnik(Roba roba, Valuta valuta, BigDecimal cena, Boolean aktivna) {
		this.roba = roba;
		this.valuta = valuta;
		this.cena = cena;
		this.aktivna = aktivna;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CENOVNIK_ID", unique = true, nullable = false)
	public Integer getCenovnikId() {
		return this.cenovnikId;
	}

	public void setCenovnikId(Integer cenovnikId) {
		this.cenovnikId = cenovnikId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROBA_ID")
	public Roba getRoba() {
		return this.roba;
	}

	public void setRoba(Roba roba) {
		this.roba = roba;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VALUTA_ID")
	public Valuta getValuta() {
		return this.valuta;
	}

	public void setValuta(Valuta valuta) {
		this.valuta = valuta;
	}

	@Column(name = "CENA", precision = 15, scale = 2)
	public BigDecimal getCena() {
		return this.cena;
	}

	public void setCena(BigDecimal cena) {
		this.cena = cena;
	}

	@Column(name = "AKTIVNA")
	public Boolean getAktivna() {
		return this.aktivna;
	}

	public void setAktivna(Boolean aktivna) {
		this.aktivna = aktivna;
	}

}
