package com.sargije.web.poslovanje.model;
// Generated Apr 25, 2017 4:34:49 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Roba generated by hbm2java
 */
@Entity
@Table(name = "ROBA",  schema = "PUBLIC", catalog = "POSLOVANJE")
public class Roba implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4249916522464916629L;
	private Long robaId;
	private VrstaRobe vrstaRobe;
	@NotNull
	@Size(min=2, max=150)
	private String robaNaziv;
	//private Set<PorudzbenicaStavke> porudzbenicaStavkes = new HashSet<PorudzbenicaStavke>(0);
	private Set<RobaCenovnik> robaCenovniks = new HashSet<RobaCenovnik>(0);
	private Set<Magacin> magacins = new HashSet<Magacin>(0);

	public Roba() {
	}

	public Roba(VrstaRobe vrstaRobe, String robaNaziv,// Set<PorudzbenicaStavke> porudzbenicaStavkes,
			Set<RobaCenovnik> robaCenovniks, Set<Magacin> magacins) {
		this.vrstaRobe = vrstaRobe;
		this.robaNaziv = robaNaziv;
		//this.porudzbenicaStavkes = porudzbenicaStavkes;
		this.robaCenovniks = robaCenovniks;
		this.magacins = magacins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROBA_ID", unique = true, nullable = false)
	public Long getRobaId() {
		return this.robaId;
	}

	public void setRobaId(Long robaId) {
		this.robaId = robaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VRSTA_ROBE_ID")
	public VrstaRobe getVrstaRobe() {
		return this.vrstaRobe;
	}

	public void setVrstaRobe(VrstaRobe vrstaRobe) {
		this.vrstaRobe = vrstaRobe;
	}

	@Column(name = "ROBA_NAZIV", length = 200)
	public String getRobaNaziv() {
		return this.robaNaziv;
	}

	public void setRobaNaziv(String robaNaziv) {
		this.robaNaziv = robaNaziv;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roba")
	public Set<PorudzbenicaStavke> getPorudzbenicaStavkes() {
		return this.porudzbenicaStavkes;
	}

	public void setPorudzbenicaStavkes(Set<PorudzbenicaStavke> porudzbenicaStavkes) {
		this.porudzbenicaStavkes = porudzbenicaStavkes;
	}
*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roba")
	public Set<RobaCenovnik> getRobaCenovniks() {
		return this.robaCenovniks;
	}

	public void setRobaCenovniks(Set<RobaCenovnik> robaCenovniks) {
		this.robaCenovniks = robaCenovniks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roba")
	public Set<Magacin> getMagacins() {
		return this.magacins;
	}

	public void setMagacins(Set<Magacin> magacins) {
		this.magacins = magacins;
	}

}
