package com.sargije.web.poslovanje.model;
// Generated Apr 25, 2017 4:34:49 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Valuta generated by hbm2java
 */
@Entity
@Table(name = "VALUTA",  schema = "PUBLIC", catalog = "POSLOVANJE")
public class Valuta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1886041495275136537L;
	private Long valutaId;
	private String valutaNaziv;
	private String valutaOznaka;
	private Set<Korisnik> korisniks = new HashSet<Korisnik>(0);
	private Set<RobaCenovnik> robaCenovniks = new HashSet<RobaCenovnik>(0);

	public Valuta() {
	}

	public Valuta(String valutaNaziv) {
		this.valutaNaziv = valutaNaziv;
	}

	public Valuta(String valutaNaziv, String valutaOznaka, Set<Korisnik> korisniks, Set<RobaCenovnik> robaCenovniks) {
		this.valutaNaziv = valutaNaziv;
		this.valutaOznaka = valutaOznaka;
		this.korisniks = korisniks;
		this.robaCenovniks = robaCenovniks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "VALUTA_ID", unique = true, nullable = false)
	public Long getValutaId() {
		return this.valutaId;
	}

	public void setValutaId(Long valutaId) {
		this.valutaId = valutaId;
	}

	@Column(name = "VALUTA_NAZIV", nullable = false, length = 20)
	public String getValutaNaziv() {
		return this.valutaNaziv;
	}

	public void setValutaNaziv(String valutaNaziv) {
		this.valutaNaziv = valutaNaziv;
	}

	@Column(name = "VALUTA_OZNAKA", length = 3)
	public String getValutaOznaka() {
		return this.valutaOznaka;
	}

	public void setValutaOznaka(String valutaOznaka) {
		this.valutaOznaka = valutaOznaka;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "valuta")
	public Set<Korisnik> getKorisniks() {
		return this.korisniks;
	}

	public void setKorisniks(Set<Korisnik> korisniks) {
		this.korisniks = korisniks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "valuta")
	public Set<RobaCenovnik> getRobaCenovniks() {
		return this.robaCenovniks;
	}

	public void setRobaCenovniks(Set<RobaCenovnik> robaCenovniks) {
		this.robaCenovniks = robaCenovniks;
	}

}
