package com.sargije.web.poslovanje.model;
// Generated Apr 25, 2017 4:34:49 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * VrstaRobe generated by hbm2java
 */
@Entity
@Table(name = "VRSTA_ROBE",  schema = "PUBLIC", catalog = "POSLOVANJE")
public class VrstaRobe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1936127518846477851L;
	private Integer vrstaRobeId;
	@NotNull
	@Size(min=2, max=150)
	private String vrstaRobeNaziv;
	private Set<Roba> robas = new HashSet<Roba>(0);

	public VrstaRobe() {
	}

	public VrstaRobe(String vrstaRobeNaziv, Set<Roba> robas) {
		this.vrstaRobeNaziv = vrstaRobeNaziv;
		this.robas = robas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "VRSTA_ROBE_ID", unique = true, nullable = false)
	public Integer getVrstaRobeId() {
		return this.vrstaRobeId;
	}

	public void setVrstaRobeId(Integer vrstaRobeId) {
		this.vrstaRobeId = vrstaRobeId;
	}

	@Column(name = "VRSTA_ROBE_NAZIV", length = 200)
	public String getVrstaRobeNaziv() {
		return this.vrstaRobeNaziv;
	}

	public void setVrstaRobeNaziv(String vrstaRobeNaziv) {
		this.vrstaRobeNaziv = vrstaRobeNaziv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vrstaRobe")
	public Set<Roba> getRobas() {
		return this.robas;
	}

	public void setRobas(Set<Roba> robas) {
		this.robas = robas;
	}

}
